// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/requirements.proto

package fr.pantheonsorbonne.cri.requirements;

public interface AgentConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requirements.AgentConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectName = 1;</code>
   */
  String getProjectName();
  /**
   * <code>string projectName = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();

  /**
   * <code>string projectGHPath = 2;</code>
   */
  String getProjectGHPath();
  /**
   * <code>string projectGHPath = 2;</code>
   */
  com.google.protobuf.ByteString
      getProjectGHPathBytes();
}
