// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/requirements.proto

package fr.pantheonsorbonne.cri.requirements;

public interface RequirementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requirements.Requirement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string issueURI = 2;</code>
   */
  String getIssueURI();
  /**
   * <code>string issueURI = 2;</code>
   */
  com.google.protobuf.ByteString
      getIssueURIBytes();
}
